# dvc.yaml
stages:
  convert:
    cmd: python -m scripts.dataset_converter --subset_size 100 --version v1 --output_path data/raw/servicenow_qa.json
    deps:
      - scripts/dataset_converter.py
    outs:
      - data/raw/servicenow_qa.json

  preprocess:
    cmd: python -m src.data.preprocess data/raw/servicenow_qa.json data/processed/servicenow_preprocessed.json --config configs/data/data_processing.json
    deps:
      - src/data/preprocess.py
      - data/raw/servicenow_qa.json
      - configs/data/data_processing.json
    outs:
      - data/processed/servicenow_preprocessed.json

  validate:
    cmd: python -m src.data.validate data/processed/servicenow_preprocessed.json --output data/validation/servicenow_valid.json
    deps:
      - src/data/validate.py
      - data/processed/servicenow_preprocessed.json
    outs:
      - data/validation/servicenow_valid.json

  tokenize:
    cmd: python -m src.data.tokenize data/validation/servicenow_valid.json data/processed/servicenow_tokenized.json --config configs/data/data_processing.json --model Qwen/Qwen2.5-7B-Instruct
    deps:
      - src/data/tokenize.py
      - data/validation/servicenow_valid.json
      - configs/data/data_processing.json
    outs:
      - data/processed/servicenow_tokenized.json

  split:
    cmd: python -m src.data.load data/processed/servicenow_tokenized.json --output_dir data/processed/splits
    deps:
      - src/data/load.py
      - data/processed/servicenow_tokenized.json
    outs:
      - data/processed/splits/train.json
      - data/processed/splits/val.json
      - data/processed/splits/test.json
