[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.pylint.messages_control]
disable = "C0111,C0103,C0303,W1201,W1202"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
