# Cloud Training Configuration for Qwen2.5 LoRA Fine-tuning

# Base model configuration
model:
  base_model_name: "Qwen/Qwen2.5-7B-Instruct"
  model_max_length: 2048
  load_in_8bit: false  # Using 4-bit quantization instead
  load_in_4bit: true   # Enable 4-bit quantization for QLoRA
  trust_remote_code: true
  use_flash_attention: true

# LoRA configuration
lora:
  r: 16  # LoRA attention dimension
  alpha: 32  # LoRA alpha parameter (scaling)
  dropout: 0.05  # Dropout probability for LoRA layers
  # Target modules to apply LoRA
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  bias: "none"  # Whether to train bias parameters
  modules_to_save: []  # Modules to save aside from LoRA adapters
  lora_path: null  # Path to existing LoRA adapters to continue training

# QLoRA configuration
qlora:
  use_qlora: true  # Whether to use QLoRA
  bits: 4  # Quantization bits
  quant_type: "nf4"  # Quantization type
  double_quant: true  # Use double quantization
  compute_dtype: "float16"  # Compute dtype for quantization

# Training parameters
training:
  per_device_train_batch_size: 1  # Batch size per GPU for training
  per_device_eval_batch_size: 1  # Batch size per GPU for evaluation
  gradient_accumulation_steps: 16  # Number of updates steps to accumulate
  num_train_epochs: 3  # Number of training epochs
  max_steps: -1  # Max steps to train (overrides epochs if > 0)
  logging_steps: 10  # Log training metrics every X steps
  save_steps: 100  # Save checkpoint every X steps
  eval_steps: 100  # Run evaluation every X steps
  warmup_steps: 10  # Learning rate warmup steps
  learning_rate: 5e-5  # Initial learning rate
  max_grad_norm: 1.0  # Max gradient norm for gradient clipping
  lr_scheduler_type: "cosine"  # Learning rate scheduler type
  weight_decay: 0.01  # Weight decay for AdamW optimizer

# Training loop settings
settings:
  seed: 42  # Random seed for reproducibility
  bf16: true  # Use bfloat16 precision if available
  fp16: false  # Use fp16 precision if bf16 not available
  tf32: true  # Use tf32 if on NVIDIA Ampere+ GPUs
  report_to: "mlflow"  # Report to MLflow and WandB
  deepspeed: "configs/training/ds_config_zero2.json" # DeepSpeed configuration

# MLflow tracking settings
mlflow:
  experiment_name: "qwen2.5-7b-lora-finetuning"
  run_name: null  # MLflow run name (if null, auto-generated)
  tracking_uri: "http://localhost:5000"  # MLflow tracking server URI
  registry_uri: "sqlite:///mlflow/registry.db"  # MLflow model registry

# Data settings
data:
  train_file: "s3://llm-finetuning-rahman-1234/data/processed/servicenow-qa_tokenized_train.pt"
  validation_file: "s3://llm-finetuning-rahman-1234/data/processed/servicenow-qa_tokenized_val.pt"
  preprocessing_num_workers: 4

# Output settings
output:
  output_dir: "models/qwen2.5-7b-lora"
  save_strategy: "steps"
  s3_output_path: "s3://llm-finetuning-rahman-1234/models/"
  hub_model_id: null
  push_to_hub: false
